pytest app/tests/ 
uvicorn app.main:app --port 8000

Тесты могут не пройти, т.к. использовал SQLite и инит моделей при старте приложения - и когда запускается тестовый клиент - бд сформироваться не успевает и тест кидает ошибку (в эндпоинте есть подключение к БД). Тесты написаны как ответ к задаче и логически верные (по моему :))
